[package]
name = "whisp"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.16"
hound = "3.5.1"
reqwest = { version = "0.12.24", features = ["blocking", "multipart"] }
tokio = { version = "1.48", features = ["full"] }
arboard = "3.6"
dotenvy = "0.15.7"
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.143"
